name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/backend/PollSpark/PollSpark.csproj
    
    - name: Build
      run: dotnet build src/backend/PollSpark/PollSpark.csproj --no-restore
    
    - name: Test
      run: dotnet test src/backend/PollSpark/PollSpark.csproj --no-build --verbosity normal 